"""Arabic dictionary loader — maps word → (Arabic definition, English definition).

Used by synth_corpus.py to enrich labels: each synthesized handwritten image gets
the full Arabic word PLUS Arabic + English definitions from a dictionary. Lets
you later train richer models (image → word + meaning, or image → translation).

Primary format — a flat JSON file:

    {
      "كتاب": {"ar": "...", "en": "book", "pos": "noun"},
      "مدرسة": {"ar": "...", "en": "school", "pos": "noun"},
      ...
    }

Source: Wiktionary via kaikki.org. The underlying extractor is
tatuylonen/wiktextract on GitHub (MIT licensed). kaikki.org hosts pre-built
JSONL dumps generated by that tool — ~150k Arabic entries with English glosses
and, where present, Arabic definitions.

Quickstart:
    python dictionary.py fetch --out ar_dictionary.json
    python synth_corpus.py --dictionary ar_dictionary.json ...
"""

from __future__ import annotations
import json
import os
from typing import Optional

from solution import NORMALIZE


def _normalize(word: str) -> str:
    """Canonical form for lookup — matches solution.py's label normalization."""
    return word.translate(NORMALIZE).strip()


class ArabicDictionary:
    """In-memory Arabic dictionary with normalization-aware lookup."""

    def __init__(self, path: str):
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"Dictionary not found: {path}. "
                "Grab one from https://kaikki.org/dictionary/Arabic/ "
                "or build your own flat JSON {word: {ar, en}}.")
        with open(path, encoding='utf-8') as f:
            raw = json.load(f)
        # Index by normalized key so 'كتاب' and 'كِتاب' both hit.
        self._entries: dict[str, dict] = {}
        for word, entry in raw.items():
            key = _normalize(word)
            if key and key not in self._entries:
                self._entries[key] = {
                    'ar': entry.get('ar'),
                    'en': entry.get('en'),
                    'pos': entry.get('pos'),
                    'surface': word,          # the exact form as stored
                }
        print(f"ArabicDictionary: {len(self._entries)} entries loaded from {path}")

    def __contains__(self, word: str) -> bool:
        return _normalize(word) in self._entries

    def __len__(self) -> int:
        return len(self._entries)

    def lookup(self, word: str) -> Optional[dict]:
        """Return {'ar', 'en', 'pos', 'surface'} or None."""
        return self._entries.get(_normalize(word))

    def ar_def(self, word: str) -> str:
        e = self.lookup(word)
        return (e or {}).get('ar') or ''

    def en_def(self, word: str) -> str:
        e = self.lookup(word)
        return (e or {}).get('en') or ''

    def pos_def(self, word: str) -> str:
        e = self.lookup(word)
        return (e or {}).get('pos') or ''


# ── Kaikki (Wiktionary) converter ─────────────────────────────────────────────
def build_from_kaikki(jsonl_path: str, out_json: str) -> None:
    """Convert kaikki.org Arabic JSONL dump → flat {word: {ar, en, pos}} JSON.

    Each kaikki line is one sense-group for one word. We keep the first
    Arabic gloss (from senses[].glosses) and the first English translation
    (from translations[] or senses[].glosses if the target is already English).
    """
    out: dict[str, dict] = {}
    with open(jsonl_path, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            word = rec.get('word', '').strip()
            if not word:
                continue
            # Arabic gloss — Wiktionary's Arabic edition defines words in Arabic.
            # For the English Wiktionary, glosses are English.
            senses = rec.get('senses') or []
            ar_gloss = ''
            en_gloss = ''
            for s in senses:
                for g in (s.get('glosses') or []):
                    # Classify by MAJORITY script over letter chars — glosses
                    # like "verbal noun of كَتَبَ (kataba)" contain one Arabic
                    # reference but are fundamentally English.
                    letters = [c for c in g if c.isalpha()]
                    if not letters:
                        continue
                    ar_chars = sum(1 for c in letters if '\u0600' <= c <= '\u06FF')
                    if ar_chars * 2 > len(letters):
                        ar_gloss = ar_gloss or g
                    else:
                        en_gloss = en_gloss or g
                if ar_gloss and en_gloss:
                    break
            # English translations list (only present when the source is the
            # Arabic Wiktionary dump cross-linked to English).
            for tr in (rec.get('translations') or []):
                if (tr.get('lang_code') or tr.get('lang', '').lower()) in ('en', 'english'):
                    en_gloss = en_gloss or tr.get('word') or ''
                    if en_gloss:
                        break
            prev = out.get(word)
            entry = {
                'ar': (prev or {}).get('ar') or ar_gloss or None,
                'en': (prev or {}).get('en') or en_gloss or None,
                'pos': (prev or {}).get('pos') or rec.get('pos') or None,
            }
            out[word] = entry
    with open(out_json, 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(f"Built {len(out)} dictionary entries → {out_json}")


# ── Downloader ────────────────────────────────────────────────────────────────
KAIKKI_URL_GZ = ('https://kaikki.org/dictionary/Arabic/'
                 'kaikki.org-dictionary-Arabic.jsonl.gz')
KAIKKI_URL = ('https://kaikki.org/dictionary/Arabic/'
              'kaikki.org-dictionary-Arabic.jsonl')


def download_kaikki(out_jsonl: str = 'kaikki_arabic.jsonl',
                    url: str = KAIKKI_URL_GZ) -> str:
    """Download kaikki.org's Arabic Wiktionary JSONL dump.

    If `url` points at the .gz variant (~40 MB), the file is streamed through
    gzip so the output is plain JSONL. Defaults to the .gz URL because the
    uncompressed dump is ~400 MB and far slower to transfer.
    """
    import urllib.request
    if os.path.exists(out_jsonl):
        size_mb = os.path.getsize(out_jsonl) / 1e6
        print(f"{out_jsonl} already exists ({size_mb:.1f} MB) — skipping download. "
              f"Delete it to re-download.")
        return out_jsonl
    print(f"Downloading {url}\n  → {out_jsonl}")

    # Probe remote size for progress reporting.
    try:
        with urllib.request.urlopen(url, timeout=30) as probe:
            total = int(probe.headers.get('Content-Length', 0))
    except Exception:
        total = 0

    is_gz = url.endswith('.gz')
    chunk = 1 << 15  # 32 KB
    done = 0
    import gzip
    with urllib.request.urlopen(url, timeout=60) as resp, \
         open(out_jsonl, 'wb') as fout:
        src = gzip.GzipFile(fileobj=resp) if is_gz else resp
        while True:
            buf = src.read(chunk)
            if not buf:
                break
            fout.write(buf)
            done += len(buf)
            if total and not is_gz:
                pct = 100.0 * done / total
                print(f"  {done/1e6:7.1f} / {total/1e6:.1f} MB  ({pct:5.1f}%)",
                      end='\r', flush=True)
            else:
                # For .gz we know the compressed total, but `done` counts
                # decompressed bytes — print both for orientation.
                print(f"  {done/1e6:7.1f} MB (decompressed)",
                      end='\r', flush=True)
    print()
    return out_jsonl


def fetch(out_json: str = 'ar_dictionary.json',
          jsonl_path: str = 'kaikki_arabic.jsonl',
          url: str = KAIKKI_URL_GZ,
          keep_jsonl: bool = True) -> None:
    """Download kaikki dump and convert to flat JSON in one step."""
    download_kaikki(jsonl_path, url)
    build_from_kaikki(jsonl_path, out_json)
    if not keep_jsonl:
        os.remove(jsonl_path)
        print(f"Removed {jsonl_path} (keep_jsonl=False).")


if __name__ == '__main__':
    import sys, io, argparse
    import paths
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest='cmd', required=True)

    p_fetch = sub.add_parser('fetch',
                             help='Download kaikki Arabic JSONL and convert to '
                                  'flat JSON in one step.')
    p_fetch.add_argument('--out', default=paths.DICTIONARY_JSON)
    p_fetch.add_argument('--jsonl', default=paths.KAIKKI_JSONL,
                         help='Local path for the raw kaikki dump.')
    p_fetch.add_argument('--url', default=KAIKKI_URL_GZ,
                         help='Default is the gzipped .jsonl.gz (~40 MB). '
                              'Pass the plain .jsonl URL if your client '
                              'cannot stream gzip.')
    p_fetch.add_argument('--discard_jsonl', action='store_true',
                         help='Delete the raw JSONL after conversion.')

    p_download = sub.add_parser('download',
                                help='Only download the raw JSONL.')
    p_download.add_argument('--out', default=paths.KAIKKI_JSONL)
    p_download.add_argument('--url', default=KAIKKI_URL_GZ)

    p_kaikki = sub.add_parser('from_kaikki',
                              help='Convert a local kaikki JSONL file → flat JSON.')
    p_kaikki.add_argument('jsonl')
    p_kaikki.add_argument('--out', default=paths.DICTIONARY_JSON)

    p_test = sub.add_parser('test', help='Load a dict and try some lookups.')
    p_test.add_argument('path')

    args = p.parse_args()
    if args.cmd == 'fetch':
        fetch(out_json=args.out, jsonl_path=args.jsonl, url=args.url,
              keep_jsonl=not args.discard_jsonl)
    elif args.cmd == 'download':
        download_kaikki(args.out, args.url)
    elif args.cmd == 'from_kaikki':
        build_from_kaikki(args.jsonl, args.out)
    elif args.cmd == 'test':
        d = ArabicDictionary(args.path)
        for w in ['كتاب', 'مدرسة', 'قمر', 'أزرق', 'ولد', 'غير_موجود']:
            e = d.lookup(w)
            print(f"{w:12s} → {e}")
